name: deploy-deno
on: [push]

jobs:
  deploy:
    name: deploy-deno
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.17.0

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: use-kfc-serve # TODO: replace with Deno Deploy project name
          entrypoint: main.ts
          root: serve
