name: slogen-addon

on:
  issues:
    types: [labeled]

jobs:
  addon:
    if: github.event.label.name == 'slogen' && github.event.issue.body != ''
    runs-on: ubuntu-latest
    steps:
      - name: call kfc serve
        run: |
          curl -v -H 'Content-Type: application/json' -X POST https://use-kfc-serve.deno.dev/store -d '{"token": "${{ secrets.WRITE_TOKEN }}", "id": "${{ github.event.issue.number }}", "content": "${{ github.event.issue.body }}", "createUser": "${{ github.event.issue.user.login }}"}'
