name: slogen-addon

on:
  issues:
    types: [labeled]

jobs:
  addon:
    if: github.event.label.name == 'slogen' && github.event.issue.body != ''
    runs-on: ubuntu-latest
    steps:
      - name: call kfc serve
        run: |
          curl -v -X POST https://use-kfc-serve.deno.dev/store -d 'token=${{ secrets.WRITE_TOKEN }}' -d 'id=${{ github.event.issue.number }}' -d 'content=${{ github.event.issue.body }}' -d 'createUser=${{ github.event.issue.user.login }}'
